### ISSUE TITLE
glyphicons are not loaded

### ISSUE THREAD

**Issue by GhaziTriki** [mconf/api-mate#15]
There is a 404 error for those files
http://mconf.github.io/fonts/glyphicons-halflings-regular.woff
http://mconf.github.io/fonts/glyphicons-halflings-regular.ttf

**Comment by daronco** [comment]
Something weird happen on GitHub Pages in the previous deploy and I had to move the assets to the root folder to fix it, but forgot to move the glyphicons.

Just deployed it again and everything is fine.
